paths:
  data_dir: 'path/to/icecube_kaggle'
  output_dir: 'path/to/icecube_kaggle/memmapped'
  sensor_geometry_path: 'path/to/sensor_geometry.csv'

data:
  batch_size: 200000
  seq_length: 192
  n_doms: 5160

splits:
  train:
    start_at_batch: 1
    stop_at_batch: 650
    include_truth: true
    target_dtype: 'float16'

  eval:
    start_at_batch: 651
    stop_at_batch: 656
    include_truth: true
    target_dtype: 'float16'

  test:
    start_at_batch: 657
    stop_at_batch: 659
    include_truth: false
    target_dtype: 'float16'
